### PR TITLE
Add Typescript defs

### PR DESCRIPTION
**Pull request by madeleineostoja**
Just a small one to add a Typescript declaration

### CODE REVIEW

**Comment by andyjansson** [comment]
Hi Sean! 
The definition seem to be missing the optional `precision` argument. Also, I believe literal types to check the arguments would be a good addition.

**Comment by andyjansson** [comment]
Closed due to inactivity.

**Comment by madeleineostoja** [comment]
Hey sorry I’ve been slammed this week, I’ll add those changes on the weekend 👍

Also yep string literal for the options would def be a good idea, oversight on my part.

**Comment by madeleineostoja** [comment]
Updated the definition to add the precision prop, and exported `CSSUnits` as a string literal to check against

**Pull request merged**
